### ISSUE TITLE
We cannot expect unrelated routers/devices on the path to apply specific behavior

### ISSUE THREAD

**Issue by gorryfair** [ietf-6man/hbh-processing#20]
Comments to the adoption call noted:

Eric V: Some comments on Ole's side question:
- no, we cannot expect unrelated routers/devices on the path to apply specific behavior (= waste CPU/memory/power/CO2) on random packets without some compensation, which requires some contract with source & destination(s)... Contractual networking is a research topic. BTW, I also do not expect/hope any router/device on the path to drop/modify extension headers for the very same reason
- as you wrote, many extension headers will only be processed by nodes (source & dest mainly) trusting each other's (i.e., my own definition of 'limited domain')
- within my own definition of limited domain, extension headers are the obvious way to extend IP features, which is what I really want to keep

**Comment by bobhinden** [comment]
The authors expectations are that some hop-by-hop options will be processed across the Internet while others will only be processed in a limited domain (e.g., where there is a specific service made available in that network segment that relies on one or more hop-by-hop options).

**Comment by gorryfair** [comment]
Add to end of section 4, before last para,

**Comment by gorryfair** [comment]
New text will be present in the next revision.
