### ISSUE TITLE
New options MUST NOT be defined that require Slow Path processing?

### ISSUE THREAD

**Issue by gorryfair** [ietf-6man/hbh-processing#21]
Comments to the adoption call noted:

Eric V:  I am not supporting "New options MUST NOT be defined that require Slow Path processing"... 
But this is "only" a call for adoption and rev -01 diff has demonstrated that Bob & Gory are listening to the WG feedback. Even with this flexibility and the text quality, I am not supporting putting constraints on the evolution of HbH, hence not supporting the adoption of this document.

Others also queried whether this is MUST?

**Comment by gorryfair** [comment]
Editors: Could change to SHOULD NOT, that would be consistent with the text later in this section about needing justification.

**Comment by bobhinden** [comment]
Changed to SHOULD NOT in what will become -01 draft.

**Comment by bobhinden** [comment]
Text was added to the editor's version to resolve this issue, and will appear as IETF draft -01.
