### ISSUE TITLE
Did RFC8200 make a difference to deployed practice?

### ISSUE THREAD

**Issue by gorryfair** [ietf-6man/hbh-processing#6]
Comments to the adoption call noted:
Fernando Gont:   Section 4, page 5:
>    Unfortunately, this did not improve the processing of Hop-by-Hop
>    options and did not significantly improve deployment and use in the
>    Internet.  Essentially, it only documented how they were being used
>    in the Internet at the time RFC8200 was published.

Has enough time elapsed  to be able to tell if the RFC8200 made a
difference or not?

**Comment by bobhinden** [comment]
Text in -01 updated to discuss that RFC8200 was not intended to change current behavior.

**Comment by bobhinden** [comment]
Text was added to the editor's version to resolve this issue, and will appear as IETF draft -01.
